server:
  port: 8761
eureka:
#  instance:
#    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false

#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/